# This file was generated by GoReleaser. DO NOT EDIT.
cask "mallard" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "64d2e0d66c203bd58f63d778761c39560fc55d540650c473d30d95c10efeb48a"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db3ded8df3f4b8545ff1961441f819b9f15d3afaea61d6f214682458ca983c70"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9555e40667855d7a0829596d0de9599b2b57d21c503075315e71d645ccbebd62"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "112cde40246cb11ef5f4082bcc6fbfc1c54520ddb80419124c44fc6e07a8b29e"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mallard"
  desc "Claude Code toolkit for PrestaShop development — skills, commands, and agents."
  homepage "https://mallard.educalvolopez.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mallard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mallard"]
    end
  end

  # No zap stanza required

end
