# This file was generated by GoReleaser. DO NOT EDIT.
cask "mallard" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "402942036e58cbc4d51a664ddd33138c8a4b9c266af7ba02911340baf2a6aec3"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb04771b6b5c0901deac44e62440be5c18f1df967462d68f72e11dc10d70f695"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e1961ca9344ea3c313e6f745e17d95bb326f0f7e3814b32fa0ecd76a908374b"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d93f8afbad7042ece505e00fc651a7a74944fc6306070acef8f46e398b625128"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mallard"
  desc "Claude Code toolkit for PrestaShop development — skills, commands, and agents."
  homepage "https://mallard.educalvolopez.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mallard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mallard"]
    end
  end

  # No zap stanza required

end
