# This file was generated by GoReleaser. DO NOT EDIT.
cask "mallard" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "a979f7fa546d6766be3169496541d7bbdb0921ef979cfa56d84d97449b29775e"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cefc41044fd932260637280d9534dc177064820fad0f030cdcee50ee2841fc7b"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1b1b988642fbdb04d2d74db49b8b81d42e9bf5ba286cb209b8ecdb8f6c21620"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "19c6f0be82b827b392a74b44970f03bccc45fec3023ca8a6ea5f6cd86d70528f"
      url "https://github.com/educlopez/mallard/releases/download/v#{version}/mallard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mallard"
  desc "Claude Code toolkit for PrestaShop development — skills, commands, and agents."
  homepage "https://mallard.educalvolopez.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mallard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mallard"]
    end
  end

  # No zap stanza required

end
