# This file was generated by GoReleaser. DO NOT EDIT.
cask "ui-craft" do
  version "1.0.14"

  on_macos do
    on_intel do
      sha256 "81efdb367b9113ec83e491c1c91ffe6cac3938618c07eeacbf679c6eb67a6141"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30f9a6111baf6328d4b734a5093461352032ef1521bc41e6c46f9fa4a64dbc22"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "345e8f2c76c99787ede5411b87b3f73eaef3873fadce759b4d70ef0f41c4a98c"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a1aa1252ea83e282b75cd9cee5502656582899415ea9f0c5d5609520c99aea7"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ui-craft"
  desc "ui-craft CLI — install the UI Craft design system into any AI agent harness"
  homepage "https://skills.smoothui.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ui-craft"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/ui-craft")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ui-craft"]
    end
  end

  # No zap stanza required

end
