# This file was generated by GoReleaser. DO NOT EDIT.
cask "ui-craft" do
  version "1.0.9"

  on_macos do
    on_intel do
      sha256 "5f17b8dd786bf1179cd39c7f818cef736ac1080187b75a655e6bc43fb2cc70ff"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "035497da4de4a917d57c25781844f1de6f522faee1831550b3142129d913b8c9"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3708e5a1ee6a126ce4e4a2958fa20bc8d3f148913c1da38b09a5432bcf8c7fa5"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "af37dd04c5edde9d363c83544e64f2edb9a5bfa8adf434519394b1341701a219"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ui-craft"
  desc "ui-craft CLI — install the UI Craft design system into any AI agent harness"
  homepage "https://skills.smoothui.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ui-craft"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/ui-craft")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ui-craft"]
    end
  end

  # No zap stanza required

end
