# This file was generated by GoReleaser. DO NOT EDIT.
cask "ui-craft" do
  version "1.0.20"

  on_macos do
    on_intel do
      sha256 "b6e60cfa11fc46706a201ebe1130c26eed7635da33b5ced2040aa3e803efeaee"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f3dd718521ca4346503098f608c60fe000c0674724f44902d68879fc0b6ed0e"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fe7dd367a96a9fd46b14434d48d021812fade6e1ad86540fbb6d8b3f391e9a0"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc299eb4a3905b28396830546bf981673f21f47fa3cb63658acefe9884e8f736"
      url "https://github.com/educlopez/ui-craft/releases/download/v#{version}/ui-craft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ui-craft"
  desc "ui-craft CLI — install the UI Craft design system into any AI agent harness"
  homepage "https://skills.smoothui.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ui-craft"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/ui-craft")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ui-craft"]
    end
  end

  # No zap stanza required

end
